#################### default parameters ################################
# favicon
favicon = "images/developer.jpg"
# logo
logo = "images/favicon.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "100px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Hydrogen"
# preloader
preloader = true
# search
search = false
# main sections
mainSections = ["blog"]
# image gallery shortcode
image_gallery = true
# copyright
theme_copyright = true
copyright = "Copyright by your_company"
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script= ""

# contact info
[contact_info]
# contact form action
contact_form_action = "#" # contact form works with https://airform.io

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "75ea92c2-a135-4f5c-8b44-54f9ddc30745" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# Valine Comment
[valine_comment]
enable = true
appId = "" # replace this code with yours [ex: QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI]
appKey = "" # replace this code with yours [ex: WBmoGyJtbqUswvfLh6L8iEBr]
# language = "change language translation from `i18n`"
avatar = "" # see : https://valine.js.org/en/avatar.html
pageSize = 10 # will show 10 comments per page
visitor = true
highlight = true # Code highlighting
recordIP = true # Record reviewer IP.
enableQQ = false # https://valine.js.org/en/configuration.html#enableQQ
# serverURLs = "" # https://leancloud.your_website.com
# Check Valine's official documentation here - https://valine.js.org/en/configuration.html

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Boilerplate", "Hugo", "Themefisher", "GetHugoThemes"]
description = "This is meta description"
author = "Themefisher"
image = "images/favicon.png" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook"  # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://facebook.com"

[[social]]
title = "twitter"
icon = "fab fa-twitter"  # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"